name: multiple_windows

environment:
  sdk: ^3.8.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: 60tfp7
