name: multi_window_internal
description: Samples for experimenting with multiple views.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-180.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
